# n.b kitchen-dokken works exclusively with Chef i.e there's no Cinc support
# Chef Infra Client cannot execute without accepting the license - erm, no

# <% require_relative '.kitchen_patch' %>
# <% require_relative '.kitchen_common' %>

driver:
  cinc_version: <%= cinc_version %>
  name: docker
  privileged: true
  volume:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro

transport:
  name: docker

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: <%= cinc_version %>

platforms:
- name: ubuntu
  driver_config:
    platform: ubuntu
    dockerfile: dockerfiles/ubuntu:<%= ubuntu_version %>
    run_command: /lib/systemd/systemd
    build_options:
      tag: kitchen-ubuntu:<%= ubuntu_version %>
- name: oracle
  driver_config:
    platform: rhel
    dockerfile: dockerfiles/oracle:<%= oracle_version %>
    run_command: /lib/systemd/systemd
    build_options:
      tag: kitchen-oracle:<%= oracle_version %>

suites:
- name: observer
  attributes:
    elrond:
      network: test
      version: <%= elrond_version %>
      node:
        log_level: '*:INFO'
      nodes:
      - id: 0
      - id: 1
      staking:
        agency: TestKitchen
      keybase:
        identity: mrstaker
  run_list:
  - recipe[spec::default]
  - recipe[elrond::default]
- name: validator
  attributes:
    elrond:
      network: test
      version: <%= elrond_version %>
      node:
        log_level: '*:INFO'
      nodes:
      - id: 0
        validator: true
        key_manager: :elrond_keyvault
      staking:
        agency: TestKitchen
      keybase:
        identity: mrstaker
  run_list:
  - recipe[spec::default]
  - recipe[spec::test_vault]
  - recipe[elrond::default]
