# n.b kitchen-dokken works exclusively with Chef i.e there's no Cinc support
# Chef Infra Client cannot execute without accepting the license - erm, no

# <% require_relative '.kitchen_patch' %>
# <% require_relative '.kitchen_common' %>

driver:
  cinc_version: <%= versions[:cinc] %>
  name: docker
  privileged: true
  volume:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro

transport:
  name: docker

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: <%= versions[:cinc] %>

platforms:
- name: ubuntu
  driver_config:
    platform: ubuntu
    dockerfile: dockerfiles/ubuntu:<%= versions[:ubuntu] %>
    run_command: /lib/systemd/systemd
    build_options:
      tag: kitchen-ubuntu:<%= versions[:ubuntu] %>
- name: oracle
  driver_config:
    platform: rhel
    dockerfile: dockerfiles/oracle:<%= versions[:oracle] %>
    run_command: /lib/systemd/systemd
    build_options:
      tag: kitchen-oracle:<%= versions[:oracle] %>

suites:
- name: observer
  attributes:
    elrond:
      network: <%= ENV['ELROND_NETWORK'] || 'test' %>
      version: <%= versions[:elrond] %>
      node:
        log_level: '*:INFO'
      nodes:
      - id: 0
      - id: 1
      staking:
        agency: TestKitchen
      keybase:
        identity: mrstaker
  run_list:
  - recipe[spec::default]
  - recipe[elrond::default]
- name: validator
  attributes:
    elrond:
      network: <%= ENV['ELROND_NETWORK'] || 'test' %>
      version: <%= versions[:elrond] %>
      node:
        log_level: '*:INFO'
      nodes:
      - id: 0
        validator: true
        key_manager: :elrond_keyvault
      staking:
        agency: TestKitchen
      keybase:
        identity: mrstaker
      keyvault:
        # these (except token) are defaults for Vault in dev mode
        address: http://127.0.0.1:8200
        token: uSmsRvfyoj4DtJdcT5ewCuPa
        path: elrond
  run_list:
  - recipe[spec::default]
  - recipe[spec::test_vault]
  - recipe[elrond::default]
