# this is literally the style recommended by rubystyle.guide despite what
# cookstyle says
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i': '[]'
    '%w': '[]'
    '%': '[]'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Metrics/BlockLength:
  Max: 150

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80
