# this is literally the style recommended by rubystyle.guide despite what
# cookstyle says
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i': '[]'
    '%w': '[]'

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80
